### ISSUE TITLE
[+orion] Bug 'hangman input o taking it as i and fills the gap'

### ISSUE THREAD

**Issue by orion-botx** [sugaroidbot/sugaroid#107]
The following answer was a given by sugaroid, and is considered as a bug. Please 
	manually review this issue, and close it if it looks unnecessary.

	user: hangman input o taking it as i and fills the gap 
    sugaroid: Oops, seems like you missed a letter.
[ ﹏ I ﹏ ﹏ ﹏ ﹏ ﹏ ﹏ ] Life: 💙💙💙

    +---+
    |   |
    0   |
   /|\  |
        |
        |
    =========

**Comment by Soul-Breaker** [comment]
This was by mistake. My sincere apologies 🙏!

**Comment by srevinsaju** [comment]
Lol
